"""Chapter 6 — Safety (first-pass scaffold: the spine test).

Angle (`measuring_livability.md` §4): *safety is broader than crime
statistics.* The series' recurring move — the headline metric points away
from the thing it claims to measure — applied to the crime rate. The claim:
**the map of crime is not the map of danger.** New Yorkers face several
different kinds of harm, generated by different forces, and they do not
co-locate.

Goal of this first pass (mirrors Ch. 2/3/4/5): validate the chapter's spine
BEFORE any visual work. Measured spine = **three kinds of harm**, each per
1,000 residents:

  1. violent crime  — person felonies (murder/rape/robbery/felony assault)
  2. traffic KI     — pedestrian + cyclist casualties (killed or injured)
  3. property crime — burglary + grand larceny (+ of motor vehicle)

Kill criterion (series standard): if any pair co-ranks |rho| >= 0.75
(Spearman, n = 59 CDs), the spine collapses. AT-RISK PAIR = violent ~
property (they share the NYPD reporting pipeline). Traffic KI is expected to
stay orthogonal to (or invert) both crime axes — that independence is the
chapter. If violent ~ property merge, the chapter becomes a clean 2-axis
"reported crime vs. traffic" story (an acceptable outcome). A perceived-
safety overlay (DOHMH CHS 2016) is added AFTER this checkpoint, not here.

Normalization (locked): per-1,000 residents (B01003), cross-axis comparable.
Traffic per-street-mile cross-check + a daytime-population caveat for
commercial cores are follow-ups, not part of the spine test.

Data window: 2022-01-01 .. 2024-12-31 (annualized), fixed so per-CD rates
are stable, not single-year noise.

Run with::

    python analyses/chapter-06/notebook.py

Outputs (out/ inside this dir):
  facts.json    Per-CD per-axis rates + the spine-test matrix.
  rankings.csv  Long-form per-CD per-axis rates + ranks (sortable for QA).

METHOD NOTE (Punch list): tract_to_cd / per_cd_population / _assign_cd are
copied from Ch. 4/5 notebooks — this is the 4th reuse; promote to
shared/access.py as its own commit. Kept as a copy here to avoid touching
Ch. 4/5 mid-kickoff.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
sys.path.insert(0, str(REPO_ROOT))

try:
    from dotenv import load_dotenv  # noqa: E402

    load_dotenv(REPO_ROOT / ".env")
except Exception:
    pass

from pipelines import (  # noqa: E402
    acs_census,
    nypd_collisions,
    nypd_complaints,
    nyc_street_centerline,
)
from shared.cd_names import name_for  # noqa: E402
from shared.zip_to_cd import is_real_cd  # noqa: E402

OUT = HERE / "out"
OUT.mkdir(exist_ok=True)

WINDOW_START = "2022-01-01"
WINDOW_END = "2024-12-31"
WINDOW_YEARS = 3.0


# ---------- shared: tract -> CD + CD population (copied from Ch. 4/5) ----------

def tract_to_cd() -> "pd.Series":
    """Series keyed by tract GEOID (11-char), value = boro_cd."""
    import geopandas as gpd
    from shared import basemap

    tracts = basemap.load("tract")
    cds = basemap.load("cd")
    cds = cds[cds["boro_cd"].apply(is_real_cd)].copy()

    centroids = gpd.GeoDataFrame(
        {"geoid": tracts["geoid"]},
        geometry=tracts.geometry.representative_point(),
        crs=tracts.crs,
    )
    joined = gpd.sjoin(
        centroids, cds[["boro_cd", "geometry"]], how="left", predicate="within"
    )
    s = joined.set_index("geoid")["boro_cd"]
    print(f"  tract->CD: {len(s)} tracts, {s.isna().sum()} unassigned")
    return s


def _acs_tract_df(table: str) -> "pd.DataFrame":
    import pandas as pd

    raw = json.loads((acs_census.fetch(table, "tract")).read_text())
    df = pd.DataFrame(raw[1:], columns=raw[0])
    df["geoid"] = df["GEO_ID"].str[-11:]
    return df.set_index("geoid")


def per_cd_population(t2c: "pd.Series") -> "pd.Series":
    """Total population per CD (sum of B01003_001E across tracts)."""
    import pandas as pd

    pop = pd.to_numeric(_acs_tract_df("B01003")["B01003_001E"], errors="coerce")
    out = pd.DataFrame({"pop": pop})
    out["borocd"] = t2c.reindex(out.index)
    series = (
        out.dropna(subset=["borocd", "pop"])
        .groupby("borocd")["pop"].sum().round(0).astype(int)
    )
    series.name = "pop"
    return series


def _assign_cd(gdf) -> "pd.Series":
    """Assign each geometry to the CD containing its representative point.

    Returns a Series aligned to ``gdf.index`` with the boro_cd (or NaN).
    """
    import geopandas as gpd
    from shared import basemap

    cds = basemap.load("cd")
    cds = cds[cds["boro_cd"].apply(is_real_cd)][["boro_cd", "geometry"]]
    pts = gpd.GeoDataFrame(
        geometry=gdf.geometry.representative_point(), crs=gdf.crs
    )
    joined = gpd.sjoin(pts, cds, how="left", predicate="within")
    return joined[~joined.index.duplicated(keep="first")]["boro_cd"]


# ---------- the three harm axes ----------

def per_cd_crime(cd_pop: "pd.Series") -> tuple["pd.Series", "pd.Series", dict]:
    """Violent and property major-felony rates per 1,000 residents, per CD.

    Annualized over the window. Returns (violent_per1k, property_per1k, meta).
    """
    import pandas as pd

    gdf = nypd_complaints.load(WINDOW_START, WINDOW_END)
    gdf = gdf.reset_index(drop=True)
    gdf["borocd"] = _assign_cd(gdf).values
    n_unassigned = int(gdf["borocd"].isna().sum())
    gdf = gdf.dropna(subset=["borocd"])

    counts = gdf.groupby(["borocd", "axis"]).size().unstack(fill_value=0)
    per1k = counts.div(cd_pop, axis=0) / WINDOW_YEARS * 1000.0
    violent = per1k.get("violent").dropna().round(3)
    prop = per1k.get("property").dropna().round(3)
    violent.name = "violent_per1k"
    prop.name = "property_per1k"

    meta = {
        "source": f"NYPD complaints {nypd_complaints.DATASET_ID}",
        "window": [WINDOW_START, WINDOW_END],
        "definition": "seven major felonies, annualized per 1,000 residents",
        "violent_ky": list(nypd_complaints.VIOLENT_KY),
        "property_ky": list(nypd_complaints.PROPERTY_KY),
        "n_complaints": int(len(gdf)),
        "n_unassigned_to_cd": n_unassigned,
        "violent_per1k_range": [float(violent.min()), float(violent.max())],
        "property_per1k_range": [float(prop.min()), float(prop.max())],
    }
    return violent, prop, meta


def per_cd_traffic(cd_pop: "pd.Series") -> tuple["pd.Series", "pd.Series", dict]:
    """Pedestrian + cyclist casualties (killed-or-injured) per 1,000
    residents, per CD; also fatalities per 100k. Annualized."""
    import pandas as pd

    gdf = nypd_collisions.load(WINDOW_START, WINDOW_END)
    gdf = gdf.reset_index(drop=True)
    gdf["borocd"] = _assign_cd(gdf).values
    n_unassigned = int(gdf["borocd"].isna().sum())
    gdf = gdf.dropna(subset=["borocd"])

    agg = gdf.groupby("borocd").agg(
        casualties=("casualties", "sum"), killed=("killed", "sum")
    )
    ki_per1k = (agg["casualties"] / cd_pop / WINDOW_YEARS * 1000.0).dropna().round(3)
    killed_per100k = (agg["killed"] / cd_pop / WINDOW_YEARS * 100000.0).dropna().round(3)
    ki_per1k.name = "traffic_ki_per1k"
    killed_per100k.name = "traffic_killed_per100k"
    casualties_per_yr = (agg["casualties"] / WINDOW_YEARS).round(2)
    casualties_per_yr.name = "casualties_per_yr"

    meta = {
        "source": f"NYPD collisions {nypd_collisions.DATASET_ID}",
        "window": [WINDOW_START, WINDOW_END],
        "definition": "pedestrian + cyclist killed OR injured (KI, not strict "
                      "KSI — public data lacks injury severity), annualized "
                      "per 1,000 residents",
        "n_crashes": int(len(gdf)),
        "n_unassigned_to_cd": n_unassigned,
        "total_casualties": int(agg["casualties"].sum()),
        "total_killed": int(agg["killed"].sum()),
        "ki_per1k_range": [float(ki_per1k.min()), float(ki_per1k.max())],
    }
    return ki_per1k, killed_per100k, casualties_per_yr, meta


def per_cd_street_miles() -> "pd.Series":
    """Centerline street-miles per CD, via the area-weighted ZIP→CD crosswalk.

    Approximate (ZIPs straddle CDs) — a denominator cross-check, not a
    headline metric. See nyc_street_centerline for the exposure rationale.
    """
    import pandas as pd

    zip_miles = nyc_street_centerline.load()
    xwalk = pd.read_csv(
        REPO_ROOT / "geographies" / "zip_cd_crosswalk.csv",
        dtype={"modzcta": str, "borocd": str},
    )
    xwalk["miles"] = xwalk["modzcta"].map(zip_miles) * xwalk["area_weight"]
    per_cd = xwalk.dropna(subset=["miles"]).groupby("borocd")["miles"].sum()
    per_cd.name = "street_miles"
    return per_cd.round(2)


def spine_test(axes: dict) -> dict:
    """Spearman rho on every axis pair; flag |rho| >= 0.75 (series kill)."""
    import itertools

    import pandas as pd

    present = {k: v for k, v in axes.items() if v is not None}
    frame = pd.DataFrame(present).dropna()
    ranks = frame.rank()
    result = {"ready": True, "n": int(len(frame)), "pairs": {}, "kill": False}
    print(f"\n[spine] n = {len(frame)} CDs")
    for a, b in itertools.combinations(present, 2):
        rho = ranks[a].corr(ranks[b])
        fires = bool(abs(rho) >= 0.75)
        result["pairs"][f"{a} ~ {b}"] = round(float(rho), 3)
        result["kill"] = result["kill"] or fires
        print(f"  {a:>22} ~ {b:<22} rho = {rho:+.3f}  "
              f"{'<<< KILL' if fires else 'ok'}")
    print(f"[spine] verdict: "
          f"{'PAIR COLLAPSES (>=0.75)' if result['kill'] else 'all pairs independent (<0.75)'}")
    return result


# Five anchors, one per borough, spanning the crime x traffic quadrants.
# 209 feared-not-deadly (BX) · 106 calm-but-deadly (MN) · 316 Brownsville the
# feared archetype (BK, Ch.2 tie) · 411 safe-both (QN, Ch.2 tie) · 503 safest
# CD citywide (SI). Midtown (105) is discussed in prose as the ambient-
# population caveat rather than anchored.
ANCHOR_CDS = ["209", "106", "316", "411", "503"]


def _safety_quadrant(violent, traffic, v_med, t_med) -> str:
    hi_v, hi_t = violent >= v_med, traffic >= t_med
    return ("feared_and_deadly" if hi_v and hi_t else
            "feared_not_deadly" if hi_v and not hi_t else
            "calm_but_deadly" if (not hi_v) and hi_t else "safe")


def render_headline(frame: "pd.DataFrame") -> dict:
    """Headline: violent-crime vs. traffic-KI scatter (the crime map is not
    the danger map) + a per-CD display-CRS geojson for <NycMap>.

    Writes:
      out/crime-vs-danger.svg   static headline scatter (fallback / repro)
      out/safety.geojson        per-CD axes + ranks + quadrant, 50-ft
                                simplified, consumed by <NycMap>/<ScatterPlot>
    """
    import matplotlib.pyplot as plt
    from shared import basemap, palette

    palette.for_matplotlib()
    f = frame.set_index("borocd")
    v_med = float(f["violent_per1k"].median())
    t_med = float(f["traffic_ki_per1k"].median())

    QCOLOR = {
        "feared_and_deadly": "#7a3a5a",   # dangerous on both
        "feared_not_deadly": palette.ALERT,   # the crime the map shows
        "calm_but_deadly": palette.ACCENT,    # the danger the map hides
        "safe": palette.MUTED,
    }
    cls = {cd: _safety_quadrant(r["violent_per1k"], r["traffic_ki_per1k"],
                                v_med, t_med)
           for cd, r in f.iterrows()}

    # ---- geojson sibling for <NycMap> ----
    cds = basemap.load("cd")
    cds = cds[cds["boro_cd"].apply(is_real_cd)].copy()
    cds["geometry"] = cds.geometry.simplify(50.0, preserve_topology=True)
    geo = cds[["boro_cd", "geometry"]].copy()
    geo["name"] = geo["boro_cd"].map(name_for)
    for col in ["violent_per1k", "traffic_ki_per1k", "property_per1k",
                "traffic_killed_per100k", "traffic_ki_per_mile"]:
        geo[col] = f[col].reindex(geo["boro_cd"].values).values
    geo["rank_violent"] = geo["violent_per1k"].rank(ascending=False, method="min").astype("Int64")
    geo["rank_traffic"] = geo["traffic_ki_per1k"].rank(ascending=False, method="min").astype("Int64")
    geo["rank_property"] = geo["property_per1k"].rank(ascending=False, method="min").astype("Int64")
    geo["quadrant"] = geo["boro_cd"].map(cls)
    geojson_path = OUT / "safety.geojson"
    basemap.to_display(geo).to_file(geojson_path, driver="GeoJSON")
    print(f"[wrote] {geojson_path}  ({geojson_path.stat().st_size:,} bytes)")

    # ---- headline scatter (static fallback) ----
    fig, ax = plt.subplots(figsize=(8.5, 8.0))
    for cd, r in f.iterrows():
        c = QCOLOR[cls[cd]]
        is_anchor = cd in ANCHOR_CDS
        ax.scatter(r["violent_per1k"], r["traffic_ki_per1k"],
                   s=80 if is_anchor else 34, c=c,
                   edgecolor=palette.TEXT if is_anchor else "none",
                   linewidth=0.8, zorder=3 if is_anchor else 2,
                   alpha=0.95 if is_anchor else 0.6)
    ax.axvline(v_med, color=palette.BORDER, lw=1, zorder=1)
    ax.axhline(t_med, color=palette.BORDER, lw=1, zorder=1)
    for cd in ANCHOR_CDS:
        r = f.loc[cd]
        ax.annotate(f"  {name_for(cd).split(' / ')[0]}",
                    xy=(r["violent_per1k"], r["traffic_ki_per1k"]),
                    fontsize=8.5, color=palette.TEXT, va="center", zorder=4)
    ax.set_xlabel("Violent crime — murder/rape/robbery/felony assault per 1,000 residents/yr")
    ax.set_ylabel("Traffic harm — pedestrians + cyclists killed or injured per 1,000 residents/yr")
    rho = f["violent_per1k"].rank().corr(f["traffic_ki_per1k"].rank())
    ax.set_title("The map of crime is not the map of danger", fontsize=15, loc="left", pad=8)
    ax.text(0.0, 1.012,
            f"NYC community districts · violent crime vs. traffic harm (ρ = {rho:+.2f})",
            transform=ax.transAxes, fontsize=9.5, color=palette.TEXT_SECONDARY,
            ha="left", va="bottom")
    svg_path = OUT / "crime-vs-danger.svg"
    fig.savefig(svg_path, bbox_inches="tight")
    plt.close(fig)
    print(f"[wrote] {svg_path}  ({svg_path.stat().st_size:,} bytes)")

    return {
        "anchors": ANCHOR_CDS,
        "violent_median_per1k": round(v_med, 3),
        "traffic_median_per1k": round(t_med, 3),
        "quadrant_counts": {k: int(v) for k, v in
                            __import__("collections").Counter(cls.values()).items()},
        "files": {"scatter_svg": svg_path.name, "geojson": geojson_path.name},
    }


def main() -> int:
    import pandas as pd

    print("[ch.6] tract->CD + CD population (ACS B01003)")
    t2c = tract_to_cd()
    cd_pop = per_cd_population(t2c)

    print("[ch.6] axes 1+3 — violent & property crime (NYPD complaints)")
    violent, prop, crime_meta = per_cd_crime(cd_pop)

    print("[ch.6] axis 2 — traffic KI (NYPD collisions, ped+cyclist)")
    traffic, killed, casualties_yr, traffic_meta = per_cd_traffic(cd_pop)

    print("[ch.6] traffic exposure cross-check — casualties per street-mile")
    street_miles = per_cd_street_miles()
    traffic_per_mile = (casualties_yr / street_miles).dropna().round(3)
    traffic_per_mile.name = "traffic_ki_per_mile"

    axes = {
        "violent_per1k": violent,
        "traffic_ki_per1k": traffic,
        "property_per1k": prop,
    }
    print("[ch.6] SPINE TEST — three kinds of harm")
    spine = spine_test(axes)

    # exposure check: does per-street-mile agree with per-resident on traffic?
    import pandas as _pd
    _tt = _pd.DataFrame({"per1k": traffic, "per_mile": traffic_per_mile}).dropna()
    traffic_norm_rho = float(_tt["per1k"].rank().corr(_tt["per_mile"].rank()))
    print(f"[ch.6] traffic per-1k ~ per-mile Spearman rho = {traffic_norm_rho:+.3f} "
          f"(high = the exposure denominator doesn't change the ranking)")

    # fear-calibration preview: which objective axis dominates the total?
    frame = pd.DataFrame({
        "violent_per1k": violent,
        "traffic_ki_per1k": traffic,
        "property_per1k": prop,
        "traffic_killed_per100k": killed,
        "traffic_ki_per_mile": traffic_per_mile,
        "street_miles": street_miles,
    })
    frame["pop"] = cd_pop.reindex(frame.index)
    frame.index.name = "borocd"
    frame = frame.reset_index()
    frame["cd_name"] = frame["borocd"].map(name_for)

    # ranks (1 = most dangerous on that axis) for QA + anchor spotting
    for col in ["violent_per1k", "traffic_ki_per1k", "property_per1k"]:
        frame[f"{col}_rank"] = frame[col].rank(ascending=False, method="min").astype("Int64")

    # quadrant class on the frame (violent x traffic) for rankings + anchors
    v_med = float(frame["violent_per1k"].median())
    t_med = float(frame["traffic_ki_per1k"].median())
    frame["quadrant"] = [
        _safety_quadrant(v, t, v_med, t_med)
        for v, t in zip(frame["violent_per1k"], frame["traffic_ki_per1k"])
    ]

    rankings = frame.sort_values("violent_per1k", ascending=False)
    rankings.to_csv(OUT / "rankings.csv", index=False)

    print("\n[ch.6] render headline (crime-vs-danger scatter + geojson)")
    render = render_headline(frame)

    fi = frame.set_index("borocd")
    anchor_table = [
        {
            "borocd": cd,
            "name": name_for(cd),
            "violent_per1k": round(float(fi.loc[cd, "violent_per1k"]), 2),
            "violent_rank": int(fi.loc[cd, "violent_per1k_rank"]),
            "traffic_ki_per1k": round(float(fi.loc[cd, "traffic_ki_per1k"]), 2),
            "traffic_rank": int(fi.loc[cd, "traffic_ki_per1k_rank"]),
            "property_per1k": round(float(fi.loc[cd, "property_per1k"]), 2),
            "property_rank": int(fi.loc[cd, "property_per1k_rank"]),
            "quadrant": fi.loc[cd, "quadrant"],
        }
        for cd in ANCHOR_CDS
    ]

    # crime-map vs danger-map divergence: how far do violent & traffic ranks move?
    fr = frame.dropna(subset=["violent_per1k_rank", "traffic_ki_per1k_rank"]).copy()
    fr["rank_gap"] = (fr["violent_per1k_rank"] - fr["traffic_ki_per1k_rank"]).abs()
    biggest_flips = fr.sort_values("rank_gap", ascending=False).head(6)

    facts = {
        "chapter": 6,
        "title_working": "Safety",
        "window": [WINDOW_START, WINDOW_END],
        "n_cds": int(frame["borocd"].nunique()),
        "normalization": "per 1,000 residents, annualized (B01003)",
        "spine_test": spine,
        "traffic_normalization_check": {
            "per1k_vs_per_mile_rho": round(traffic_norm_rho, 3),
            "note": "Spearman ρ between traffic KI per-1k-resident and per-"
                    "street-mile rankings. High ρ means the dense-core traffic "
                    "toll is not merely a resident-denominator artifact — it "
                    "survives an exposure denominator.",
        },
        "axes": {
            "violent": crime_meta,
            "traffic": traffic_meta,
        },
        "property_note": "property crime carried as a descriptive third axis; "
                         "the bodily-harm story is violent + traffic.",
        "anchors": anchor_table,
        "headline": render,
        "citywide": {
            "violent_per1k_median": round(float(violent.median()), 3),
            "traffic_ki_per1k_median": round(float(traffic.median()), 3),
            "property_per1k_median": round(float(prop.median()), 3),
        },
        "biggest_crime_vs_traffic_flips": [
            {
                "borocd": r.borocd,
                "name": r.cd_name,
                "violent_rank": int(r.violent_per1k_rank),
                "traffic_rank": int(r.traffic_ki_per1k_rank),
                "rank_gap": int(r.rank_gap),
                "violent_per1k": round(float(r.violent_per1k), 2),
                "traffic_ki_per1k": round(float(r.traffic_ki_per1k), 2),
            }
            for r in biggest_flips.itertuples()
        ],
    }
    (OUT / "facts.json").write_text(json.dumps(facts, indent=2) + "\n")
    print(f"\n[ch.6] wrote {OUT/'facts.json'} and {OUT/'rankings.csv'}")
    print(f"[ch.6] citywide medians/1k — violent {violent.median():.2f}, "
          f"traffic KI {traffic.median():.2f}, property {prop.median():.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
